name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # or your desired branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker image
      run: |
        docker build -t gcr.io/$GCP_PROJECT_ID/fastapi-app .

    - name: Log in to Google Container Registry
      run: echo ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }} | docker login -u _json_key --password-stdin https://gcr.io

    - name: Push Docker image
      run: |
        docker push gcr.io/$GCP_PROJECT_ID/fastapi-app

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy fastapi-app \
          --image gcr.io/$GCP_PROJECT_ID/fastapi-app \
          --platform managed \
          --region europe-west1 \  # Change to your preferred European region
          --allow-unauthenticated \
          --project $GCP_PROJECT_ID
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          --region europe-west1 \  # Change to your preferred European region

