name: Deploy to Google Cloud Run

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies using Pipenv
      run: |
        pip install pipenv
        pipenv install --system --deploy

    - name: Install Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Login to GAR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Setup Docker Buildx for multi-architecture builds

    - name: Push Docker image to GCR
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-app
        

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy fastapi-app \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-app \
          --platform managed \
          --region europe-west1 \
          --allow-unauthenticated \
          --project $GCP_PROJECT_ID
